services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    volumes:
      - ./storage/uploads:/app/storage/uploads

  nginx:
    image: nginx:latest
    container_name: nginx_cdn
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./storage/uploads:/app/storage/uploads:ro
    depends_on:
      - backend
